name: Deploy Backend

on:
  push:
    branches: [main, tannaz_gpt2_shakespeare]
    paths:
      - 'docker/backend/**'
      - 'k8s/03-backend.yaml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    uses: ./.github/workflows/deploy-image.yml
    with:
      image_name: ml-backend
      docker_context: docker/backend
      deployment_name: ml-backend
    secrets: inherit
